

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>Frequently Asked Questions &mdash; CATMAID 2015.7.17-dev documentation</title>
    
    <link rel="stylesheet" href="_static/jinja.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="_static/style.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     '2015.7.17-dev',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <link rel="shortcut icon" href="_static/favicon.ico"/>
    <link rel="top" title="CATMAID 2015.7.17-dev documentation" href="index.html" />
    <link rel="up" title="Administrator Documentation" href="administrator.html" />
    <link rel="next" title="Developer Documentation" href="developer.html" />
    <link rel="prev" title="Setting Up Nginx for CATMAID" href="alternative_install.html" /> 
  </head>
  <body role="document">
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="developer.html" title="Developer Documentation"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="alternative_install.html" title="Setting Up Nginx for CATMAID"
             accesskey="P">previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">CATMAID 2015.7.17-dev documentation</a> &raquo;</li>
          <li class="nav-item nav-item-1"><a href="administrator.html" accesskey="U">Administrator Documentation</a> &raquo;</li> 
      </ul>
    </div>  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="frequently-asked-questions">
<h1>Frequently Asked Questions<a class="headerlink" href="#frequently-asked-questions" title="Permalink to this headline">¶</a></h1>
<div class="section" id="i-updated-to-ubuntu-12-04-and-i-have-postgres-8-4-and-9-1-installed-on-my-system">
<h2>I updated to Ubuntu 12.04 and I have postgres 8.4 and 9.1 installed on my system<a class="headerlink" href="#i-updated-to-ubuntu-12-04-and-i-have-postgres-8-4-and-9-1-installed-on-my-system" title="Permalink to this headline">¶</a></h2>
<p>Remove all postgres version 8.4 packages (this removes also the databases).
Then change the port in /etc/postgresql/9.1/main/postgresql.conf to:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">port</span> <span class="o">=</span> <span class="mi">5432</span>
</pre></div>
</div>
<p>Restart postgres:</p>
<div class="highlight-python"><div class="highlight"><pre>sudo /etc/init.d/postgresql restart
</pre></div>
</div>
<p>Now you should be able to call the ./scripts/createuser.sh script.</p>
</div>
<div class="section" id="my-catmaid-instance-is-working-in-debug-mode-but-can-t-be-reached-in-production-what-is-the-problem">
<h2>My CATMAID instance is working in debug mode, but can&#8217;t be reached in production. What is the problem?<a class="headerlink" href="#my-catmaid-instance-is-working-in-debug-mode-but-can-t-be-reached-in-production-what-is-the-problem" title="Permalink to this headline">¶</a></h2>
<p>If you see return code 400 (Bad Request), check the <code class="docutils literal"><span class="pre">ALLOWED_HOSTS</span></code> setting in
your Django configuration file:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">django</span><span class="o">/</span><span class="n">projects</span><span class="o">/</span><span class="n">mysite</span><span class="o">/</span><span class="n">settings</span><span class="o">.</span><span class="n">py</span>
</pre></div>
</div>
<p>Since Django 1.5 this setting is present and should contain a list of all
host/domain names that your CATMAID instance is reachable under. Access will be
blocked if target host isn&#8217;t found in this list. For more detail have a look at
the <a class="reference external" href="https://docs.djangoproject.com/en/1.6/ref/settings/#allowed-hosts">Django documentation</a>.</p>
<p>Be aware that if you use Nginx and make a WSGI server available through an
<em>upstream</em> definition, the host that Django sees is the upstream&#8217;s name. So this
is what you want to add to <code class="docutils literal"><span class="pre">ALLOWED_HOSTS</span></code>. Alternatively, you can add a
<code class="docutils literal"><span class="pre">X-Forwarded-Host</span></code> header when calling the upstream in a Nginx location block
to forward the original host to Django:</p>
<div class="highlight-python"><div class="highlight"><pre>proxy_set_header X-Forwarded-Host $host;
</pre></div>
</div>
<p>If you then instruct Django to use this header by setting <code class="docutils literal"><span class="pre">USE_X_FORWARDED_HOST</span>
<span class="pre">=</span> <span class="pre">True</span></code> in <code class="docutils literal"><span class="pre">settings.py</span></code> (see <a class="reference external" href="https://docs.djangoproject.com/en/1.8/ref/settings/#use-x-forwarded-host">doc</a>),
you can add the original host name to <code class="docutils literal"><span class="pre">ALLOWED_HOSTS</span></code>.</p>
</div>
<div class="section" id="i-have-more-than-one-catmaid-instance-running-on-the-same-sub-domain-but-in-different-folders-when-i-open-different-instances-in-the-same-browser-at-the-same-time-one-session-is-always-logged-out-why">
<h2>I have more than one CATMAID instance running on the same (sub-)domain, but in different folders. When I open different instances in the same browser at the same time, one session is always logged out. Why?<a class="headerlink" href="#i-have-more-than-one-catmaid-instance-running-on-the-same-sub-domain-but-in-different-folders-when-i-open-different-instances-in-the-same-browser-at-the-same-time-one-session-is-always-logged-out-why" title="Permalink to this headline">¶</a></h2>
<p>Django uses the cookie name &#8216;sessionid&#8217; for its session information in a cookie
called &#8216;csrftoken&#8217; for CSRF information. This is fine if only one instance is
running on a certain domain. If, however, multiple instances run on the same
domain, this naming scheme fails. The same cookie name is then used for both
instances, which leads to the logout in all but one instances if the multiple
instances are opened in the same browser.</p>
<p>To fix this, either regenerate your settings.py file with a recent CATMAID
version or manually set different names for the relevant cookies in all your
<code class="docutils literal"><span class="pre">settings.py</span></code> files by overriding the variables <code class="docutils literal"><span class="pre">SESSION_COOKIE_NAME</span></code> and
<code class="docutils literal"><span class="pre">CSRF_COOKIE_NAME</span></code>. Recent CATMAID versions do this automatically, based on
the specified sub-folder.</p>
</div>
<div class="section" id="i-get-an-error-500-response-and-in-debug-mode-i-see-the-error-libhdf5-so-8-cannot-open-shared-object-file-no-such-file-or-directory-this-might-have-started-after-the-system-update">
<h2>I get an error 500 response and in debug mode I see the error &#8220;libhdf5.so.8: cannot open shared object file: No such file or directory&#8221;. This might have started after the system update.<a class="headerlink" href="#i-get-an-error-500-response-and-in-debug-mode-i-see-the-error-libhdf5-so-8-cannot-open-shared-object-file-no-such-file-or-directory-this-might-have-started-after-the-system-update" title="Permalink to this headline">¶</a></h2>
<p>Apparently, your system&#8217;s HDF5 library was changed. Therefore, the Python
bindings that are used by CATMAID have to be updated. Given you are within the
<code class="docutils literal"><span class="pre">virtualenv</span></code> and in CATMAID&#8217;s <code class="docutils literal"><span class="pre">django</span></code> directory, the following should fix
it:</p>
<div class="highlight-python"><div class="highlight"><pre>grep h5py requirements.txt | xargs pip install -I
</pre></div>
</div>
<p>This will reinstall (and recompile) the HDF5 python bindings with the version
specified in our dependency file (<code class="docutils literal"><span class="pre">requirements.txt</span></code>).</p>
</div>
<div class="section" id="i-get-an-error-500-response-and-in-debug-mode-i-see-the-error-libboost-python-so-1-56-0-cannot-open-shared-object-file-no-such-file-or-directory-or-any-other-boost-version-this-might-have-started-after-a-system-update">
<h2>I get an error 500 response and in debug mode I see the error &#8220;libboost_python.so.1.56.0: cannot open shared object file: No such file or directory&#8221;. (Or any other boost version) This might have started after a system update.*<a class="headerlink" href="#i-get-an-error-500-response-and-in-debug-mode-i-see-the-error-libboost-python-so-1-56-0-cannot-open-shared-object-file-no-such-file-or-directory-or-any-other-boost-version-this-might-have-started-after-a-system-update" title="Permalink to this headline">¶</a></h2>
<p>It seems that the Boost library was updated and therefore one module that we
depend on has to be recompiled: pgmagick. Given you are within the
<code class="docutils literal"><span class="pre">virtualenv</span></code> and in CATMAID&#8217;s <code class="docutils literal"><span class="pre">django</span></code> directory, the following should fix
it:</p>
<div class="highlight-python"><div class="highlight"><pre>grep pgmagick requirements.txt | xargs pip install -I
</pre></div>
</div>
<p>This will reinstall (and recompile) the pgmagick module, using the version
specified in our dependency file (<code class="docutils literal"><span class="pre">requirements.txt</span></code>).</p>
</div>
<div class="section" id="catmaid-stopped-working-after-postgis-update">
<span id="faq-postgis-update-problems"></span><h2>CATMAID stopped working after PostGIS update<a class="headerlink" href="#catmaid-stopped-working-after-postgis-update" title="Permalink to this headline">¶</a></h2>
<p>Updating PostGIS on your host system could cause CATMAID to stop working. You
might see errors like:</p>
<div class="highlight-python"><div class="highlight"><pre>django.core.exceptions.ImproperlyConfigured: Cannot determine PostGIS
version for database &quot;catmaid&quot;. GeoDjango requires at least PostGIS
version 1.3. Was the database created from a spatial database template?
</pre></div>
</div>
<p>This can happen when old PostGIS library files are removed and PostGIS can&#8217;t
find what it expects. To fix this, log into the CATMAID Postgres database and
update the PostGIS extension:</p>
<div class="highlight-python"><div class="highlight"><pre>sudo -u postgres psql -d &lt;CATMAID-DB-NAME&gt;
ALTER EXTENSION postgis UPDATE;
</pre></div>
</div>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper"><p class="logo"><a href="index.html">
  <img class="logo" src="_static/catmaidlogo.png" alt="Logo" align="left"/>
</a></p>
<br clear="all"/><br /><h3><a href="index.html">Home</a></h3>
<h3><a href="screenshots.html">Screenshots</a></h3>
<h3><a href="whouses.html">Who uses it?</a></h3>
<h3><a href="publications.html">Publications</a></h3>
<h3><a href="funding.html">Funding</a></h3>
<h3><a href="credits.html">Credits</a></h3>
<h3>Useful Links</h3>
<ul>
  <li><a href="http://github.com/catmaid/CATMAID">Source Code</a></li>
  <li><a href="http://github.com/catmaid/CATMAID/issues">Issues</a></li>
  <li><a href="http://groups.google.com/group/CATMAID">Mailinglist</a></li>
  <li><a href="http://fly.mpi-cbg.de/~saalfeld/catmaid/">Old page</a></li>
</ul>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17713054-5']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  <h3><a href="index.html">Table Of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">Frequently Asked Questions</a><ul>
<li><a class="reference internal" href="#i-updated-to-ubuntu-12-04-and-i-have-postgres-8-4-and-9-1-installed-on-my-system">I updated to Ubuntu 12.04 and I have postgres 8.4 and 9.1 installed on my system</a></li>
<li><a class="reference internal" href="#my-catmaid-instance-is-working-in-debug-mode-but-can-t-be-reached-in-production-what-is-the-problem">My CATMAID instance is working in debug mode, but can&#8217;t be reached in production. What is the problem?</a></li>
<li><a class="reference internal" href="#i-have-more-than-one-catmaid-instance-running-on-the-same-sub-domain-but-in-different-folders-when-i-open-different-instances-in-the-same-browser-at-the-same-time-one-session-is-always-logged-out-why">I have more than one CATMAID instance running on the same (sub-)domain, but in different folders. When I open different instances in the same browser at the same time, one session is always logged out. Why?</a></li>
<li><a class="reference internal" href="#i-get-an-error-500-response-and-in-debug-mode-i-see-the-error-libhdf5-so-8-cannot-open-shared-object-file-no-such-file-or-directory-this-might-have-started-after-the-system-update">I get an error 500 response and in debug mode I see the error &#8220;libhdf5.so.8: cannot open shared object file: No such file or directory&#8221;. This might have started after the system update.</a></li>
<li><a class="reference internal" href="#i-get-an-error-500-response-and-in-debug-mode-i-see-the-error-libboost-python-so-1-56-0-cannot-open-shared-object-file-no-such-file-or-directory-or-any-other-boost-version-this-might-have-started-after-a-system-update">I get an error 500 response and in debug mode I see the error &#8220;libboost_python.so.1.56.0: cannot open shared object file: No such file or directory&#8221;. (Or any other boost version) This might have started after a system update.*</a></li>
<li><a class="reference internal" href="#catmaid-stopped-working-after-postgis-update">CATMAID stopped working after PostGIS update</a></li>
</ul>
</li>
</ul>
<h3>Related Topics</h3>
<ul>
  <li><a href="index.html">Documentation</a><ul>
  <li><a href="administrator.html">Administrator Documentation</a><ul>
      <li>Previous: <a href="alternative_install.html" title="previous chapter">Setting Up Nginx for CATMAID</a></li>
      <li>Next: <a href="developer.html" title="next chapter">Developer Documentation</a></li>
  </ul></li>
  </ul></li>
</ul>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="footer">
      &copy; Copyright 2016, CATMAID Developers.
      Created using <a href="http://sphinx.pocoo.org/">Sphinx</a>.
    </div>
  </body>
</html>